### ISSUE TITLE
Considering all localization projects

### ISSUE THREAD

**Issue by pubudu-ranasinghe** [CodeLanka/codeLanka-Proposals#11]
I wanted to submit this as a seperate project but seeing the existing ones similar to this, I think it's better to post this here.

- What I had in mind was to create a central repository for *all things sinhala in the web*. Which will have several handpicked fonts and most importantly focus on promoting their usage and accessibility.

- The average sinhala blogger usually don't have the expertise to set up these web-fonts by themselves. So we can add WP plugins, code snippets, tutorials, starter themes to promote sinhala font usage( at the moment most of the sinhala blogs are running on outdated WP and blogger with native sinhala fonts in the OS. ).

- There is *Sinhala Font Directory*, *local language font compatibility library for android*, *Adobe Brackets Sinhala Localization* listed as separate projects here. Why not bring all these scattered individual localization projects under one umbrella. So everyone can collaborate to make a better sinhala web. This will also eliminate duplicate efforts too.

- (Sinhala wordpress?)

- (Sinhala Font CDN?)

So ultimately this can be a central hub to promote sinhala localization to make a better, beautiful sinhala web. :smile:

**Comment by hliyan** [comment]
:+1:

**Comment by pasindud** [comment]
@pubudu-ranasinghe  thanks for taking your time to post this :+1: 

@pathumego you should come in for this and post about the fonts


Are initial idea was to setup sinhala directory and then provide CDN for that, but there are some legal issues for some of them so we can only allow uses to view them but cannot distribute them.

I am all for Sinhala Wordpress :+1: 

local language font compatibility library for android, Adobe Brackets Sinhala Localisation are kind of idea that can be done under codelanka. So what we can do for localization projects have common dataset, like a word or sentence and common translation and transliteration. So other projects can refer those and do the intial translation, other custom translation would have to be done manually. (not sure whether I am answering right)

You should check this some it is something like all things sinhala for web developers.
https://github.com/CodeLanka/codeLanka-Proposals/#6-sri-lanka-developer-technical-resources

**Comment by pathumego** [comment]
@pubudu-ranasinghe Hi, Sorry about missing out this!

#Sinhala Font CDN 

This can not be realised without enough Unicode Encoded proper fonts. At the moment most of the unicode fonts available are 
- Not optimised for web use
- Licensing is complicated (ICTA fonts are under a stupid CC license, and hybrid Non Commercial)

And since google is planning to roll out Sinhala support this year, maintaining a separate CDN is actually an extra effort. If there are fonts we can get it shipped on Google Fonts. But a collection of sinhala fonts in a repo is definitely useful. As a resource. (Again there are legal issues) 

#All things sinhala in the web

This is a great idea! I will start a repo and set this up ASAP. I had this idea for a SinhalaWeb.com website. A directory of Sinhala Websites. Last year Google India launched a similar project https://www.hindiweb.com/start.html

This could be the starting point for any native language web user.

**Comment by pathumego** [comment]
I just opened a repo here https://github.com/CodeLanka/sinhala-web. I will make a simple jekyll  - GH pages website so that we can add sites easily. 

We can do something like this in Sinhala http://www.fontspring.com/support/installing_webfonts/how-do-i-use-the-webfonts

**Comment by pathumego** [comment]
@pubudu-ranasinghe You can see some interesting font related work tomo at IO :)

**Comment by keshan** [comment]
+1 for the Sinhala Web idea

**Comment by pathumego** [comment]
@keshan @pubudu-ranasinghe Done :dancers: :dancers: 

http://codelanka.github.io/sinhala-web/

**Comment by pathumego** [comment]
@pasindud Now we just need people to add websites, easy enough, maybe do a marathon :hamburger:  
So I used jekyll posts to index the sites, Since its yml we can later scrape  data if needed. And we can get a feed too :) Make an app maybe :)

**Comment by pasindud** [comment]
:+1:

**Comment by pasindud** [comment]
@pathumego we Will have to put some disclaimers

**Comment by pasindud** [comment]
@pahans you know some right

**Comment by pathumego** [comment]
@pasindud Regarding the collection and selection? Yeah I think it's important.. Can someone help?

**Comment by pathumego** [comment]
@pahans  @iamchathu  I added a simple disclaimer here. - https://github.com/CodeLanka/sinhala-web/tree/add-disclaimer

Please review, add, and merge :)

**Comment by pahans** [comment]
* isnt sinhala wordpress is already there (https://si.wordpress.org/) ? .
bhashitha and all fonts listed here are GPL licenced. (http://www.icta.lk/index.php?option=com_content&view=article&id=1497:sinhala-tamil-unicode-fonts-bhashitha-and-sritamil&catid=104:local-languages-initiative&Itemid=234&lang=en).
* fonts like malithi uni and most unicode fonts are copyrighted to Pushpananda Ekanayake. I am sure he will give permission to use his for web fonts idea.
* are you guys to coming to Google IO today? if so lets talk.

**Comment by pahans** [comment]
oh they seems to have change bhashitha licence to CC license. it was GPL before.

**Comment by pathumego** [comment]
@pahans Yep @pasindud has my number. Lets arrange to meet.

**Comment by pathumego** [comment]
@pahans 
`oh they seems to have change bhashitha licence to CC license. it was GPL before.`
Yep, still if we need to provide a proper service we need to be able to refactor and make them 'better' For last 5 months Ive been trying to work with them on this. You can imagine the rest. Its a dead end unless we go from the top level admin.

But I am up for making a web font service as long as we clarify the legal stuff. And Fonts got to be proper! I can elaborate on this when we meet :) 

`fonts like malithi uni and most unicode fonts are copyrighted to Pushpananda Ekanayake. I am sure he will give permission to use his for web fonts idea.`

Nope he is ok people using his fonts, as long as big companies don't make money out of them. Even the licensing on Malithi Web which was an ICAT project is not properly licensed. All I can tell you is he can sue anyone using his fonts including Malithi Web at any given moment. 

But he is not a bad guy. Selling fonts is his living and got to respect that. 

But there is good news :) I worked with him to liberate and release FM Abhaya under Open Fonts License with Google Fonts support. I will be presenting this work today at IO.

**Comment by pathumego** [comment]
@pasindud Actually CC Attribution is also ok, they have some basic fonts that we can ship. I have some ideas about how we can go about this.

**Comment by pubudu-ranasinghe** [comment]
Its nice to see this revived. @pathumgo as you mentioned adding to google fonts is the better than CDN. We need more fonts though. Was it you who gave the presentation about fonts at IO. (I really loved ayanna narrow).

@pahans unfortunately sinhala wp project is inactive. Last release was 2.x I think. So there must be some sinhala sites running with serious vulnerabilities. I'm not sure who were heading the sinhala wp project. Maybe we can contact them and get some more people involved in translating. I think having an active sinhala wp distribution might contribute a lot in pushing the sinhala web forward. It can be the starting point for a lot of new devs.

**Comment by pubudu-ranasinghe** [comment]
Also did you guys meet at Google IO? If so any updates on what was discussed?

**Comment by ishan-marikar** [comment]
Glad to hear about this project. I know people who would love to get involved with this. I would too, but I'm not really well versed with the Sinhala language.

To be honest, I've never really come across a truly 'beautiful' Sinhala font (although I've seen them being used anywhere but). I'm talking about the HelveticaNeue of Sinhala Fonts. We could also make the Sinhala web a beautiful place too.

@pubudu-ranasinghe I missed Google IO yet again :c

**Comment by pathumego** [comment]
@pubudu-ranasinghe Yep It was us :) Thanks for the comments. @ishan-marikar  Yep thats what we intend to do. Make beautiful Sinhala and Tamil fonts :) You can checkout `https://github.com/mooniak` for some of our font projects.

**Comment by pubudu-ranasinghe** [comment]
Btw can we have a https://gitter.im/ chat room for this? It requires a member of the organization to create one.

**Comment by pasindud** [comment]
@pubudu-ranasinghe we already had one for the org but was pvt
this is public https://gitter.im/CodeLanka/codeLanka-Proposals
