### ISSUE TITLE
[Proposal] Adobe Brackets Sinhala Localization 

### ISSUE THREAD

**Issue by iamchathu** [CodeLanka/codeLanka-Proposals#6]
Adobe Brackets is a smart extendable Code editor used by developer community.They need support to do localization.

**Comment by pasindujw** [comment]
The github file is not allowing me to edit :/ Can you help me with this issue?

**Comment by pasindud** [comment]
@iamchathu can you put up that site translating site

**Comment by KRVPerera** [comment]
Is there a particular font to do the translation...

**Comment by pasindud** [comment]
at the moment no most of them have just have done transliteration and pasted them, I think the font is noto sans. Which should ideal look into unicode too, but would be nice to get all the translation done

**Comment by iamchathu** [comment]
https://crowdin.com/project/adobe-brackets-sinhala-transla/

Register there and contribute. 

Use unicode

**Comment by KRVPerera** [comment]
Is this project cancelled..

**Comment by pasindujw** [comment]
don't think so machn

On Wed, Nov 18, 2015 at 8:53 AM, KRV PERERA <notifications@github.com>
wrote:

> Is this project cancelled..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CodeLanka/codeLanka-Proposals/issues/6#issuecomment-157593070>
> .
>



-- 
*Pasindu Upulwan Jayaweera*
Software Engineering Intern
Mobile: +94 718187375

WSO2 Inc: http://wso2.com/

**Comment by iamchathu** [comment]
Nope It's not canceled
Will add missing strings from new version soon.

**Comment by KRVPerera** [comment]
Good..
